name: openlara # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: OpenLara 
summary: Explore the Open-Source Tomb Raider Experience. # 79 char long summary
description: |
   Dive into meticulously crafted environments filled with puzzles, traps, and secrets waiting to be uncovered. 
   As Lara Croft, master the art of exploration and survival, utilizing cunning, agility, and firepower to overcome formidable challenges.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  openlara:
    command: bin/openlara-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  openlara:
    plugin: dump
    source: .
    organize:
      openlara-bin: bin/
